---
strategy: webhook
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
framework_version: 3.1.1
serverless_language: ''
polling_url: ''
polling_headers: ''
polling_body: ''
id: 319290
name: My Plugin
refresh_interval: 15
